{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "19991e75-d58d-4bde-95f3-53fe0e3cd545",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "\n",
    "\n",
    "# Answer->\n",
    "\n",
    "# When creating a custom exception in Python, it is important to inherit from the Exception class. The Exception class\n",
    "# is a built-in exception class in Python that serves as the base class for all other built-in and user-defined exception \n",
    "# classes. By inheriting from the Exception class, you can ensure that your custom exception follows the standard exception\n",
    "# hierarchy in Python.\n",
    "\n",
    "# Inheriting from the Exception class also provides a number of benefits:\n",
    "    \n",
    "# Consistency:\n",
    "#     By inheriting from the Exception class, your custom exception will follow the same API and behavior as other exceptions\n",
    "#     in Python. This makes it easier for other developers to understand and use your custom exception.\n",
    "    \n",
    "    \n",
    "# Functionality: The Exception class provides a number of methods and attributes that are useful for handling exceptions, such as __str__, args, \n",
    "#                and with_traceback. By inheriting from the Exception class, your custom exception will inherit these methods and attributes.\n",
    "# Compatibility: Many built-in exception classes in Python, such as ValueError, TypeError, and KeyError, are derived from the Exception class.\n",
    "#                By inheriting from the Exception class, your custom exception will be compatible with existing exception handling code that expects \n",
    "#                exceptions to be derived from Exception.\n",
    "        \n",
    "# Therefore, when creating a custom exception in Python, it is recommended to inherit from the Exception class to ensure consistency, functionality, and compatibility \n",
    "# with other exceptions in Python.\n",
    "\n",
    "import logging\n",
    "logging.basicConfig(filename=\"Question01.log\",filemode='w', level=logging.DEBUG, format='%(asctime)s %(message)s')\n",
    "\n",
    "class NegativeNumberError(Exception):\n",
    "    def __init__(self, message=\"Number can't be negative\"):\n",
    "        self.message = message\n",
    "        super().__init__(self.message)\n",
    "\n",
    "def calculate_square_root(number):\n",
    "    if number < 0:\n",
    "        raise NegativeNumberError()\n",
    "    return number ** 0.5\n",
    "\n",
    "try:\n",
    "    result = calculate_square_root(-4)\n",
    "except NegativeNumberError as e:\n",
    "    logging.error(e.message)\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "f54a77ba-be28-4220-92d3-9bbc69af40c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Q2. Write a python program to print Python Exception Hierarchy.\n",
    "\n",
    "# Answer->\n",
    "\n",
    "import logging\n",
    "import inspect\n",
    "logging.basicConfig(filename='Question02.log', level=logging.INFO ,filemode='w',format='%(asctime)s %(message)s')\n",
    "def treeClass(cls, ind=0):\n",
    "    logging.info('-' * ind + cls.__name__)\n",
    "    for i in cls.__subclasses__():\n",
    "        treeClass(i, ind + 3)\n",
    "logging.info(\"Hierarchy for Built-in exceptions is: \")\n",
    "inspect.getclasstree(inspect.getmro(BaseException))\n",
    "treeClass(BaseException)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "00f41813-edff-469f-beb7-da47d4e46081",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "division by zero\n",
      "could not convert string to float: 'error'\n"
     ]
    }
   ],
   "source": [
    "# Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "\n",
    "# Answer->\n",
    "\n",
    "\n",
    "# The ArithmeticError class is a built-in Python exception class that serves as a base class for all built-in exceptions \n",
    "# that arise from arithmetic operations. Some of the errors that are defined in the ArithmeticError class include:\n",
    "\n",
    "# ZeroDivisionError: Raised when an operation tries to divide a number by zero.\n",
    "\n",
    "# OverflowError: Raised when the result of an arithmetic operation exceeds the maximum representable value for a numeric type.\n",
    "\n",
    "# UnderflowError: Raised when the result of an arithmetic operation is too small to be represented by a numeric type.\n",
    "\n",
    "# FloatingPointError: Raised when an operation on floating-point numbers fails to produce a valid result, such as division by \n",
    "# zero or a NaN (Not a Number) result.\n",
    "\n",
    "#example1\n",
    "\n",
    "try :\n",
    "    2/0\n",
    "except ZeroDivisionError as e:\n",
    "    print(e)\n",
    "\n",
    "#example2\n",
    "\n",
    "try:\n",
    "    x= float('error')\n",
    "    y= float('again')\n",
    "    z=x/y\n",
    "except Exception as e:\n",
    "    print(e)\n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "58939bdf-3ac1-4394-8a03-e3e1df9071ba",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index out of bound error.\n",
      "keyError\n"
     ]
    }
   ],
   "source": [
    "# Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "\n",
    "# Answer->\n",
    "\n",
    "# The LookupError class is a built-in Python exception that serves as the base class for all lookup errors. \n",
    "# It is used to indicate that an index, key, or attribute could not be found.\n",
    "\n",
    "# The LookupError class is commonly used in situations where an operation requires a specific index, key,\n",
    "# or attribute, and that index, key, or attribute does not exist.\n",
    "\n",
    "# Two specific types of LookupError in Python are KeyError and IndexError.\n",
    "\n",
    "\n",
    "try:\n",
    "\ta = [1, 2]\n",
    "\tprint (a[3])\n",
    "except LookupError:\n",
    "\tprint (\"Index out of bound error.\")\n",
    "else:\n",
    "\tprint (\"Success\")\n",
    "    \n",
    "try:\n",
    "    my_dict = {\"name\": \"John\", \"age\": 25}\n",
    "    print(my_dict[\"gender\"]) \n",
    "except LookupError:\n",
    "    print(\"keyError\")\n",
    "    \n",
    "    \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "f9bcd754-f2fb-4588-99cd-77dc7e51952f",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "# Answer->\n",
    "\n",
    "# ImportError is a built-in Python exception that is raised when an imported module or package cannot be found or\n",
    "# loaded. It can occur for a variety of reasons, such as if the module is not installed, if the module is not in \n",
    "# the Python search path, or if there is a typo in the module name.\n",
    "\n",
    "# ModuleNotFoundError is a more specific exception that was introduced in Python 3.6. It is raised when an imported\n",
    "# module or package cannot be found. In other words, it is a subclass of ImportError that is specifically used when\n",
    "# the module or package is not found.\n",
    "\n",
    "# In earlier versions of Python (before 3.6), ImportError was raised for all cases where an imported module or package \n",
    "\n",
    "# could not be found, regardless of whether the error was due to a missing module or a misspelled module name. With the\n",
    "# introduction of ModuleNotFoundError, it is now possible to more easily distinguish between these two cases.\n",
    "\n",
    "# Both ImportError and ModuleNotFoundError are common exceptions that can occur when importing modules in Python, and they\n",
    "# often indicate that something is wrong with the code or the environment.\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "id": "fdfd77a6-36bd-4689-bb30-7369b3e854c1",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Q6. List down some best practices for exception handling in python.\n",
    "\n",
    "# Answer->\n",
    "\n",
    "\n",
    "# Use specific exceptions: Use specific exceptions wherever possible instead of using generic exceptions like Exception. This helps in writing more \n",
    "# meaningful and targeted code.\n",
    "\n",
    "# Keep it simple: Keep the try-except blocks as simple as possible. Ideally, it should contain only one or two statements.\n",
    "\n",
    "# Don't hide errors: Never suppress exceptions silently, always log them or at least print them so that you can identify and debug the issue.\n",
    "\n",
    "# Use finally: Use the finally clause to release any resources that were acquired in the try block. For example, closing a file or releasing a \n",
    "# database connection.\n",
    "\n",
    "# Be mindful of performance: Exception handling can have a performance impact, so be mindful of how many try-except blocks you use in your code.\n",
    "\n",
    "# Handle exceptions at the appropriate level: Handle exceptions at the appropriate level of abstraction. For example, if a lower-level function \n",
    "# raises an exception, it might be better to handle it in the calling function rather than in the lower-level function itself.\n",
    "\n",
    "# Use custom exceptions: Define custom exceptions for your application to make it easier to identify errors and handle them appropriately.\n",
    "\n",
    "# Avoid catching and re-raising exceptions: Avoid catching an exception and re-raising it unless you have a good reason to do so. This can make\n",
    "# it harder to debug the code and can also impact performance.\n",
    "\n",
    "# Follow Python's exception hierarchy: Follow Python's exception hierarchy to ensure that your exception handling is consistent with other Python \n",
    "# code."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b2efe855-6df7-42e5-a80b-6ffee1938487",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
